# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

exclude: |
  (?x)(
    .release|
    ^CHANGELOG.md
  )
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    - id: trailing-whitespace
    - id: check-merge-conflict
    - id: trailing-whitespace
    - id: mixed-line-ending
    - id: check-yaml
      args: [--allow-multiple-documents]
    - id: check-json
    - id: check-ast                        # Python syntax check (check that code parses as valid python)
    - id: check-added-large-files
    - id: check-symlinks
    - id: detect-aws-credentials
    - id: detect-private-key
- repo: git://github.com/antonbabenko/pre-commit-terraform
  rev: v1.50.0
  hooks:
    - id: terraform_fmt
    - id: terraform_docs
      args: ['-a --hide data-sources', '-a --hide resources',  '-a --sort-by required']

-   repo: https://github.com/thlorenz/doctoc
    rev: v2.0.1
    hooks:
    - id: doctoc
      args: [--notitle, --maxlevel=3, --update-only, --github]

- repo: git@github.com:basefarm/tfdyn_doc.git
  rev: v0.1.4
  hooks:
  - id: tfdyn_doc
    #args: [--verbose, --dryrun]